#include<stdio.h>
#include<string.h>
int main()
{
    char *a[5][8];
    a[0][0]="p";
    a[0][1]="q";
    a[0][2]="~p";
    a[0][3]="~q";
    a[0][4]="p^q";
    a[0][5]="pvq";
    a[0][6]="p->q";
    a[0][7]="p<->q";
    a[1][0]=a[2][0]="T";
    a[3][0]=a[4][0]="F";
    a[1][1]=a[3][1]="T";
    a[2][1]=a[4][1]="F";
    for(int i=1;i<5;i++)
    {
        if(strcmp(a[i][0],"T")==0)
        {
            a[i][2]="F";
        }
        else
        {
            a[i][2]="T";
        }
        if(strcmp(a[i][1],"T")==0)
        {
            a[i][3]="F";
        }
        else{
            a[i][3]="T";
        }
        if(strcmp(a[i][1],"T")==0&&strcmp(a[i][0],"T")==0)
        {
            a[i][4]="T";
        }
        else{
            a[i][4]="F";
        }
        if(strcmp(a[i][1],"F")==0&&strcmp(a[i][0],"F")==0)
        {
            a[i][5]="F";
        }
        else{
            a[i][5]="T";
        }
        if(strcmp(a[i][1],"T")==0&&strcmp(a[i][0],"F")==0)
        {
            a[i][6]="F";
        }
        else{
            a[i][6]="T";
        }
        if(strcmp(a[i][1],a[i][0])==0)
        {
            a[i][7]="T";
        }
        else{
            a[i][7]="F";
        }
    }
    for(int i=0;i<5;i++)
    {
        for(int j=0;j<8;j++)
        {
            printf("%s\t",a[i][j]);
        }
        printf("\n");
    }
    return 0;
}